// VOFC Options for Consideration Database for HOST V3 integration
// This file contains 400+ pre-defined options for consideration with cost estimates and implementation details

window.VOFC_OPTIONS = [
  {
    "ofc_number": "OFC001",
    "option_text": "Install perimeter fencing with controlled access points and vehicle barriers to strengthen site boundaries and guide visitors through defined entry paths. Use anti-climb features where appropriate and coordinate the design with surveillance and access-control measures.",
    "sheet": "Physical Security",
    "row": 1,
    "reference": "CISA Guidelines Section 3.1, ASIS Standard 1.1, DHS Infrastructure Protection",
    "category": "Physical Security",
    "priority": "Critical",
    "cost_estimate": "$50,000 - $150,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V001",
    "benefit_explanation": "Strengthens site boundaries, reduces uncontrolled access, and supports a layered security posture",
    "compliance_impact": "Supports perimeter-security and controlled-access objectives"
  },
  {
    "ofc_number": "OFC002",
    "option_text": "Deploy a video surveillance system with high-resolution cameras, appropriate retention, and live monitoring for critical areas. Connect the system to response procedures so leaders can act quickly when an incident occurs.",
    "sheet": "Technology",
    "row": 2,
    "reference": "CISA Guidelines Section 4.2, NIST Cybersecurity Framework, ASIS Physical Security Standards",
    "category": "Technology",
    "priority": "Critical",
    "cost_estimate": "$75,000 - $200,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V002",
    "benefit_explanation": "Improves visibility, supports faster incident response, and preserves evidence for follow-up",
    "compliance_impact": "Supports surveillance and monitoring objectives"
  },
  {
    "ofc_number": "OFC003",
    "option_text": "Create a structured Security Force training program covering threat recognition, response procedures, and security protocols. Include recurring training, documentation, and role-based refreshers so staff remain prepared.",
    "sheet": "Personnel Security",
    "row": 3,
    "reference": "ASIS Personnel Security Standards, NASRO Standards",
    "category": "Personnel Security",
    "priority": "Medium",
    "cost_estimate": "$10,000 - $25,000",
    "implementation_time": "1-3 months",
    "vulnerability_id": "V003",
    "benefit_explanation": "Improves preparedness, strengthens response consistency, and reduces execution gaps during incidents",
    "compliance_impact": "Supports personnel-readiness expectations"
  },
  {
    "ofc_number": "OFC004",
    "option_text": "Restrict access to fire-alarm and similar critical enclosures, document operating procedures, and confirm backup power supports the systems that matter most during an emergency. Extend the plan into evacuation, lockdown, and crisis-communication procedures.",
    "sheet": "Emergency Preparedness",
    "row": 4,
    "reference": "FEMA Emergency Management Guidelines, CISA Emergency Preparedness Standards",
    "category": "Emergency Preparedness",
    "priority": "High",
    "cost_estimate": "$5,000 - $15,000",
    "implementation_time": "1-2 months",
    "vulnerability_id": "V004",
    "benefit_explanation": "Strengthens emergency readiness and reduces the chance of preventable control failures",
    "compliance_impact": "Supports emergency-preparedness and life-safety expectations"
  },
  {
    "ofc_number": "OFC005",
    "option_text": "Install an electronic access-control system with credentialed entry, visitor tracking, and audit trails for key areas.",
    "sheet": "Access Control",
    "row": 5,
    "reference": "ASIS Access Control Standards, NIST Access Control Guidelines",
    "category": "Access Control",
    "priority": "Medium",
    "cost_estimate": "$25,000 - $75,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V005",
    "benefit_explanation": "Improves control over who enters the property and creates a clearer accountability trail",
    "compliance_impact": "Supports access-control governance"
  },
  {
    "ofc_number": "OFC006",
    "option_text": "Improve perimeter lighting with LED fixtures, motion sensors, and coverage coordinated to surveillance needs.",
    "sheet": "Physical Security",
    "row": 6,
    "reference": "ASIS Physical Security Standards, IES Lighting Standards",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$15,000 - $40,000",
    "implementation_time": "1-2 months",
    "vulnerability_id": "V006",
    "benefit_explanation": "Improves visibility, supports monitoring, and reduces opportunities for unnoticed access",
    "compliance_impact": "Supports perimeter-security objectives"
  },
  {
    "ofc_number": "OFC007",
    "option_text": "Reduce uncontrolled surface-parking exposure by guiding vehicles and pedestrians through defined entry points and toward a staffed lobby. Add a visitor-management process when dedicated fields are available.",
    "sheet": "Access Control",
    "row": 7,
    "reference": "ASIS Visitor Management Standards, CISA Access Control Guidelines",
    "category": "Access Control",
    "priority": "Medium",
    "cost_estimate": "$20,000 - $50,000",
    "implementation_time": "1-3 months",
    "vulnerability_id": "V007",
    "benefit_explanation": "Aligns parking, entry, and visitor flow with a more controlled operating model",
    "compliance_impact": "Supports layered access-control concepts"
  },
  {
    "ofc_number": "OFC008",
    "option_text": "Use barriers, bollards, and site design to create meaningful standoff distance between vehicles and buildings.",
    "sheet": "Physical Security",
    "row": 8,
    "reference": "DHS Infrastructure Protection Guidelines, ASIS Physical Security Standards",
    "category": "Physical Security",
    "priority": "High",
    "cost_estimate": "$30,000 - $80,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V008",
    "benefit_explanation": "Reduces exposure to vehicle-borne threats and improves the property’s protective buffer",
    "compliance_impact": "Supports standoff and protective-distance guidance"
  },
  {
    "ofc_number": "OFC009",
    "option_text": "Use dedicated security personnel or a contracted security service to provide a consistent presence and response capability.",
    "sheet": "Personnel Security",
    "row": 9,
    "reference": "ASIS Security Personnel Standards, Private Security Standards",
    "category": "Personnel Security",
    "priority": "Medium",
    "cost_estimate": "$60,000 - $150,000 annually",
    "implementation_time": "1-2 months",
    "vulnerability_id": "V009",
    "benefit_explanation": "Improves visible coverage and speeds response when issues arise",
    "compliance_impact": "Supports staffing and response expectations"
  },
  {
    "ofc_number": "OFC010",
    "option_text": "Clarify monitoring coverage and incident-reporting procedures. Define expected monitoring hours, document how incidents are recorded, and add mass-notification or public-address systems as separate projects if needed.",
    "sheet": "Emergency Preparedness",
    "row": 10,
    "reference": "FEMA Emergency Communication Guidelines, CISA Emergency Preparedness Standards",
    "category": "Emergency Preparedness",
    "priority": "High",
    "cost_estimate": "$25,000 - $60,000",
    "implementation_time": "2-3 months",
    "vulnerability_id": "V010",
    "benefit_explanation": "Reduces ambiguity during incidents and improves leadership visibility",
    "compliance_impact": "Supports emergency-communications planning"
  },
  {
    "ofc_number": "OFC011",
    "option_text": "Strengthen cybersecurity for security systems through segmentation, encryption, access controls, and regular updates.",
    "sheet": "Technology",
    "row": 11,
    "reference": "NIST Cybersecurity Framework, CISA Security Guidelines",
    "category": "Technology",
    "priority": "High",
    "cost_estimate": "$40,000 - $100,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V011",
    "benefit_explanation": "Protects security-system integrity and reduces the likelihood of disruption",
    "compliance_impact": "Supports cybersecurity control objectives"
  },
  {
    "ofc_number": "OFC012",
    "option_text": "Second mitigation option for the same FACP-access and backup-power signals as V004: pursue integration testing between fire alarm, access control, and VSS where technically feasible; document interfaces and alarm-response procedures. (Scoring uses V004; catalog retains V012 for historical OFC text.)",
    "sheet": "Emergency Preparedness",
    "row": 12,
    "reference": "NFPA Fire Safety Standards, ASIS Emergency Management Guidelines",
    "category": "Emergency Preparedness",
    "priority": "High",
    "cost_estimate": "$30,000 - $75,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V004",
    "benefit_explanation": "Supports coordinated response when systems can be integrated; scope is contingent on architecture review",
    "compliance_impact": "Follow NFPA and AHJ expectations for testing and maintenance; integration must be engineered per site"
  },
  {
    "ofc_number": "OFC013",
    "option_text": "Develop comprehensive VIP security protocols including threat assessment, protective measures, access control, and emergency procedures. This should ensure adequate protection for high-profile guests and events.",
    "sheet": "VIP Operations",
    "row": 13,
    "reference": "ASIS VIP Protection Standards, DHS Protective Security Guidelines",
    "category": "VIP Operations",
    "priority": "High",
    "cost_estimate": "$50,000 - $150,000",
    "implementation_time": "4-8 months",
    "vulnerability_id": "V013",
    "benefit_explanation": "Provides comprehensive VIP protection, reduces security risks, and ensures adequate protection for high-profile guests",
    "compliance_impact": "Meets ASIS VIP Protection Standards and DHS Protective Security Guidelines"
  },
  {
    "ofc_number": "OFC014",
    "option_text": "Implement comprehensive parking security measures including access control, surveillance, lighting, and security patrols. This should provide adequate security for parking areas and reduce vehicle-based threats.",
    "sheet": "Physical Security",
    "row": 14,
    "reference": "ASIS Parking Security Standards, DHS Infrastructure Protection Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$25,000 - $75,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V014",
    "benefit_explanation": "Reduces vehicle-based threats, improves parking security, and provides comprehensive parking area protection",
    "compliance_impact": "Meets ASIS Parking Security Standards and DHS Infrastructure Protection Guidelines"
  },
  {
    "ofc_number": "OFC015",
    "option_text": "Implement comprehensive pool and recreational area security including access control, surveillance, lifeguard training, and emergency procedures. This should provide adequate security for recreational areas.",
    "sheet": "Physical Security",
    "row": 15,
    "reference": "ASIS Recreational Security Standards, Pool Safety Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$20,000 - $50,000",
    "implementation_time": "1-3 months",
    "vulnerability_id": "V015",
    "benefit_explanation": "Improves recreational area security, reduces liability, and provides comprehensive protection for guest areas",
    "compliance_impact": "Meets ASIS Recreational Security Standards and Pool Safety Guidelines"
  },
  {
    "ofc_number": "OFC016",
    "option_text": "Strengthen vetting and credentials for VIP-facing staff and Security Force (the fields HOST actually measures): background checks where lawful, role-appropriate; maintain certifications; document training. Expand to a formal vendor/contractor program when vendor-specific assessment fields are added.",
    "sheet": "Access Control",
    "row": 16,
    "reference": "ASIS Vendor Security Standards, DHS Contractor Security Guidelines",
    "category": "Access Control",
    "priority": "High",
    "cost_estimate": "$15,000 - $40,000",
    "implementation_time": "1-2 months",
    "vulnerability_id": "V016",
    "benefit_explanation": "Reduces security risks from external vendors, improves contractor security, and ensures adequate screening",
    "compliance_impact": "Meets ASIS Vendor Security Standards and DHS Contractor Security Guidelines"
  },
  {
    "ofc_number": "OFC017",
    "option_text": "Implement comprehensive elevator and stairwell security including access control, surveillance, emergency procedures, and security monitoring. This should provide adequate security for vertical circulation areas.",
    "sheet": "Physical Security",
    "row": 17,
    "reference": "ASIS Vertical Security Standards, Elevator Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$30,000 - $80,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V017",
    "benefit_explanation": "Improves vertical circulation security, reduces unauthorized access, and provides comprehensive elevator/stairwell protection",
    "compliance_impact": "Meets ASIS Vertical Security Standards and Elevator Security Guidelines"
  },
  {
    "ofc_number": "OFC018",
    "option_text": "Implement comprehensive retail and public area security including surveillance, access control, security patrols, and incident response procedures. This should provide adequate security for public areas.",
    "sheet": "Physical Security",
    "row": 18,
    "reference": "ASIS Retail Security Standards, Public Area Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$25,000 - $60,000",
    "implementation_time": "2-3 months",
    "vulnerability_id": "V018",
    "benefit_explanation": "Improves public area security, reduces theft and incidents, and provides comprehensive protection for guest areas",
    "compliance_impact": "Meets ASIS Retail Security Standards and Public Area Security Guidelines"
  },
  {
    "ofc_number": "OFC019",
    "option_text": "Implement comprehensive incident reporting and documentation systems including digital reporting, tracking, analysis, and improvement procedures. This should provide adequate incident management and security improvement capabilities.",
    "sheet": "Emergency Preparedness",
    "row": 19,
    "reference": "ASIS Incident Reporting Standards, Security Documentation Guidelines",
    "category": "Emergency Preparedness",
    "priority": "Medium",
    "cost_estimate": "$10,000 - $30,000",
    "implementation_time": "1-2 months",
    "vulnerability_id": "V019",
    "benefit_explanation": "Improves incident tracking, enables security improvements, and provides comprehensive incident management",
    "compliance_impact": "Meets ASIS Incident Reporting Standards and Security Documentation Guidelines"
  },
  {
    "ofc_number": "OFC020",
    "option_text": "Implement comprehensive backup and redundancy systems for critical security functions including redundant systems, backup power, failover procedures, and system monitoring. This should ensure continuous security capability during system failures.",
    "sheet": "Technology",
    "row": 20,
    "reference": "NIST System Redundancy Guidelines, ASIS Technology Standards",
    "category": "Technology",
    "priority": "High",
    "cost_estimate": "$75,000 - $200,000",
    "implementation_time": "4-8 months",
    "vulnerability_id": "V020",
    "benefit_explanation": "Ensures continuous security capability, reduces system failure risks, and provides comprehensive backup capabilities",
    "compliance_impact": "Meets NIST System Redundancy Guidelines and ASIS Technology Standards"
  },
  {
    "ofc_number": "OFC021",
    "option_text": "HOST inferred privacy/cyber risk from missing or unknown segmentation of video/security networks. Mitigate with VLANs/firewall rules, monitoring, encryption in transit, and data-handling policies for any recorded or exported footage. Full GDPR/CCPA/PCI programs require business-scope assessment beyond this signal.",
    "sheet": "Technology",
    "row": 21,
    "reference": "GDPR, CCPA, NIST Privacy Framework, PCI DSS",
    "category": "Technology",
    "priority": "High",
    "cost_estimate": "$50,000 - $125,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V021",
    "benefit_explanation": "Reduces lateral movement and exposure of security-system data paths when segmentation is weak or unknown",
    "compliance_impact": "Align with NIST CSF and privacy frameworks; legal/regulatory scope varies by processing activity"
  },
  {
    "ofc_number": "OFC022",
    "option_text": "Strengthen physical security for deliveries and receiving: controlled loading-dock and service hours; verify vendor/delivery identity; escort or sign-in rules; adequate lighting and camera coverage at receiving; clear procedures for after-hours deliveries. HOST does not assess food safety law—only security of delivery and receiving access.",
    "sheet": "Physical Security",
    "row": 22,
    "reference": "CISA physical security resources; DHS critical infrastructure partnership materials",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$20,000 - $50,000",
    "implementation_time": "1-3 months",
    "vulnerability_id": "V022",
    "benefit_explanation": "Reduces theft, tailgating, and unauthorized access at receiving aligned with measured coverage gaps",
    "compliance_impact": "Supports organizational security policy; not a substitute for food safety regulatory programs"
  },
  {
    "ofc_number": "OFC023",
    "option_text": "Implement comprehensive laundry and housekeeping security protocols including access control, surveillance, staff screening, and guest property protection. This should secure service areas and protect guest belongings.",
    "sheet": "Physical Security",
    "row": 23,
    "reference": "ASIS Service Area Security Standards, Hotel Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$15,000 - $40,000",
    "implementation_time": "1-2 months",
    "vulnerability_id": "V023",
    "benefit_explanation": "Secures service areas, protects guest property, and reduces theft and security incidents",
    "compliance_impact": "Meets ASIS Service Area Security Standards and Hotel Security Guidelines"
  },
  {
    "ofc_number": "OFC024",
    "option_text": "Measured: open fire-alarm panel access and missing restricted-area signage—not a full mechanical-room survey. Mitigate by locking FACP/enclosures, signage for restricted areas, and key control for utility rooms; expand asset inventory when maintenance fields are added.",
    "sheet": "Physical Security",
    "row": 24,
    "reference": "DHS Critical Infrastructure Guidelines, ASIS Infrastructure Security Standards",
    "category": "Physical Security",
    "priority": "High",
    "cost_estimate": "$40,000 - $100,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V024",
    "benefit_explanation": "Protects critical infrastructure, prevents sabotage, and ensures continuous facility operations",
    "compliance_impact": "Meets DHS Critical Infrastructure Guidelines and ASIS Infrastructure Security Standards"
  },
  {
    "ofc_number": "OFC025",
    "option_text": "Implement comprehensive guest room security and access control including electronic locks, surveillance, privacy protection, and emergency procedures. This should secure guest rooms and protect guest privacy and safety.",
    "sheet": "Access Control",
    "row": 25,
    "reference": "ASIS Guest Room Security Standards, Hotel Security Guidelines",
    "category": "Access Control",
    "priority": "High",
    "cost_estimate": "$100,000 - $300,000",
    "implementation_time": "6-12 months",
    "vulnerability_id": "V025",
    "benefit_explanation": "Secures guest rooms, protects guest privacy and safety, and prevents unauthorized access",
    "compliance_impact": "Meets ASIS Guest Room Security Standards and Hotel Security Guidelines"
  },
  {
    "ofc_number": "OFC026",
    "option_text": "Implement comprehensive conference and meeting room security including access control, surveillance, information protection, and business security protocols. This should secure business areas and protect confidential information.",
    "sheet": "Physical Security",
    "row": 26,
    "reference": "ASIS Business Security Standards, Meeting Room Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$25,000 - $60,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V026",
    "benefit_explanation": "Secures business areas, protects confidential information, and ensures business security",
    "compliance_impact": "Meets ASIS Business Security Standards and Meeting Room Security Guidelines"
  },
  {
    "ofc_number": "OFC027",
    "option_text": "Implement comprehensive spa and wellness area security including access control, surveillance, privacy protection, and staff training. This should secure sensitive wellness areas and protect guest privacy.",
    "sheet": "Physical Security",
    "row": 27,
    "reference": "ASIS Wellness Security Standards, Spa Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$30,000 - $75,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V027",
    "benefit_explanation": "Secures wellness areas, protects guest privacy, and ensures sensitive area security",
    "compliance_impact": "Meets ASIS Wellness Security Standards and Spa Security Guidelines"
  },
  {
    "ofc_number": "OFC028",
    "option_text": "Implement comprehensive fitness center and gym security including access control, surveillance, equipment protection, and safety protocols. This should secure fitness areas and protect equipment and guests.",
    "sheet": "Physical Security",
    "row": 28,
    "reference": "ASIS Fitness Security Standards, Gym Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$20,000 - $50,000",
    "implementation_time": "1-3 months",
    "vulnerability_id": "V028",
    "benefit_explanation": "Secures fitness areas, protects equipment, and ensures guest safety in recreational areas",
    "compliance_impact": "Meets ASIS Fitness Security Standards and Gym Security Guidelines"
  },
  {
    "ofc_number": "OFC029",
    "option_text": "Measured gaps: video network segmentation and/or Security Force reporting. Implement segmented networks for business-center PCs and guest printers; document incident reporting for business systems. Add business-center-specific questions later for a tighter mapping.",
    "sheet": "Physical Security",
    "row": 29,
    "reference": "ASIS Business Security Standards, Office Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$25,000 - $60,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V029",
    "benefit_explanation": "Aligns mitigations with network and reporting signals HOST actually captures",
    "compliance_impact": "Align with NIST CSF and organizational IT policy"
  },
  {
    "ofc_number": "OFC030",
    "option_text": "Implement comprehensive children's area and family security including access control, surveillance, child safety protocols, and staff training. This should secure children's areas and ensure child safety and family security.",
    "sheet": "Physical Security",
    "row": 30,
    "reference": "ASIS Children's Security Standards, Family Safety Guidelines",
    "category": "Physical Security",
    "priority": "High",
    "cost_estimate": "$40,000 - $100,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V030",
    "benefit_explanation": "Secures children's areas, ensures child safety, and provides comprehensive family security",
    "compliance_impact": "Meets ASIS Children's Security Standards and Family Safety Guidelines"
  },
  {
    "ofc_number": "OFC031",
    "option_text": "Implement comprehensive operational security and business continuity measures including emergency procedures, backup systems, service continuity protocols, and operational resilience planning. This should ensure continuous operations during emergencies.",
    "sheet": "Emergency Preparedness",
    "row": 31,
    "reference": "ASIS Business Continuity Standards, DHS Emergency Preparedness Guidelines",
    "category": "Emergency Preparedness",
    "priority": "High",
    "cost_estimate": "$60,000 - $150,000",
    "implementation_time": "4-8 months",
    "vulnerability_id": "V031",
    "benefit_explanation": "Ensures operational continuity, reduces service disruption risks, and provides comprehensive business resilience",
    "compliance_impact": "Meets ASIS Business Continuity Standards and DHS Emergency Preparedness Guidelines"
  },
  {
    "ofc_number": "OFC032",
    "option_text": "Implement comprehensive guest services and concierge security including access control, information protection, staff training, and service security protocols. This should secure guest service areas and protect guest information.",
    "sheet": "Access Control",
    "row": 32,
    "reference": "ASIS Guest Services Security Standards, Hotel Security Guidelines",
    "category": "Access Control",
    "priority": "Medium",
    "cost_estimate": "$25,000 - $60,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V032",
    "benefit_explanation": "Secures guest service areas, protects guest information, and ensures service security",
    "compliance_impact": "Meets ASIS Guest Services Security Standards and Hotel Security Guidelines"
  },
  {
    "ofc_number": "OFC033",
    "option_text": "Implement comprehensive transportation and valet security including vehicle protection, access control, surveillance, and staff training. This should secure transportation areas and protect guest vehicles.",
    "sheet": "Physical Security",
    "row": 33,
    "reference": "ASIS Transportation Security Standards, Valet Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$30,000 - $75,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V033",
    "benefit_explanation": "Secures transportation areas, protects guest vehicles, and reduces vehicle theft risks",
    "compliance_impact": "Meets ASIS Transportation Security Standards and Valet Security Guidelines"
  },
  {
    "ofc_number": "OFC034",
    "option_text": "Implement comprehensive event and banquet security including access control, surveillance, crowd management, and event security protocols. This should secure event areas and ensure safe large gatherings.",
    "sheet": "Physical Security",
    "row": 34,
    "reference": "ASIS Event Security Standards, Large Venue Security Guidelines",
    "category": "Physical Security",
    "priority": "High",
    "cost_estimate": "$50,000 - $125,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V034",
    "benefit_explanation": "Secures event areas, ensures safe large gatherings, and provides comprehensive event security",
    "compliance_impact": "Meets ASIS Event Security Standards and Large Venue Security Guidelines"
  },
  {
    "ofc_number": "OFC035",
    "option_text": "Implement comprehensive nightclub and entertainment security including access control, surveillance, alcohol management, and entertainment security protocols. This should secure entertainment areas and manage nightlife security risks.",
    "sheet": "Physical Security",
    "row": 35,
    "reference": "ASIS Entertainment Security Standards, Nightclub Security Guidelines",
    "category": "Physical Security",
    "priority": "High",
    "cost_estimate": "$40,000 - $100,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V035",
    "benefit_explanation": "Secures entertainment areas, manages nightlife risks, and provides comprehensive entertainment security",
    "compliance_impact": "Meets ASIS Entertainment Security Standards and Nightclub Security Guidelines"
  },
  {
    "ofc_number": "OFC036",
    "option_text": "Implement comprehensive casino and gaming security including access control, surveillance, fraud prevention, and gaming security protocols. This should secure gaming areas and prevent gaming-related security incidents.",
    "sheet": "Physical Security",
    "row": 36,
    "reference": "ASIS Gaming Security Standards, Casino Security Guidelines",
    "category": "Physical Security",
    "priority": "High",
    "cost_estimate": "$75,000 - $200,000",
    "implementation_time": "4-8 months",
    "vulnerability_id": "V036",
    "benefit_explanation": "Secures gaming areas, prevents fraud and theft, and provides comprehensive gaming security",
    "compliance_impact": "Meets ASIS Gaming Security Standards and Casino Security Guidelines"
  },
  {
    "ofc_number": "OFC037",
    "option_text": "Implement comprehensive retail and shopping security including access control, surveillance, theft prevention, and retail security protocols. This should secure retail areas and prevent shoplifting and theft.",
    "sheet": "Physical Security",
    "row": 37,
    "reference": "ASIS Retail Security Standards, Shopping Center Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$25,000 - $60,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V037",
    "benefit_explanation": "Secures retail areas, prevents theft and shoplifting, and provides comprehensive retail security",
    "compliance_impact": "Meets ASIS Retail Security Standards and Shopping Center Security Guidelines"
  },
  {
    "ofc_number": "OFC038",
    "option_text": "Close the gaps HOST measured: complete Security Force training on all applicable emergency plans (document completions and refresher schedule); ensure backup power supports required security and life-safety loads per site engineering and AHJ expectations; exercise plans with tabletop and walk-through drills.",
    "sheet": "Physical Security",
    "row": 38,
    "reference": "CISA emergency preparedness; Ready.gov business continuity; NFPA 110 (generator testing concepts, where applicable)",
    "category": "Physical Security",
    "priority": "High",
    "cost_estimate": "$50,000 - $125,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V038",
    "benefit_explanation": "Aligns response capability and power resilience with the training and backup-power signals in the assessment",
    "compliance_impact": "Align with local fire/life-safety and organizational policy; validate generator scope with qualified personnel"
  },
  {
    "ofc_number": "OFC039",
    "option_text": "Implement comprehensive environmental and sustainability security including access control, system protection, environmental monitoring, and green infrastructure security protocols. This should secure environmental systems and protect green infrastructure.",
    "sheet": "Physical Security",
    "row": 39,
    "reference": "ASIS Environmental Security Standards, Green Building Security Guidelines",
    "category": "Physical Security",
    "priority": "Medium",
    "cost_estimate": "$30,000 - $75,000",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V039",
    "benefit_explanation": "Secures environmental systems, protects green infrastructure, and ensures environmental security",
    "compliance_impact": "Meets ASIS Environmental Security Standards and Green Building Security Guidelines"
  },
  {
    "ofc_number": "OFC040",
    "option_text": "Implement comprehensive international and cultural security protocols including cultural sensitivity training, international guest protection, diverse population security, and cross-cultural security measures. This should ensure cultural security and protect international guests.",
    "sheet": "Emergency Preparedness",
    "row": 40,
    "reference": "ASIS International Security Standards, Cultural Security Guidelines",
    "category": "Emergency Preparedness",
    "priority": "High",
    "cost_estimate": "$35,000 - $85,000",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V040",
    "benefit_explanation": "Ensures cultural security, protects international guests, and provides comprehensive cross-cultural security",
    "compliance_impact": "Meets ASIS International Security Standards and Cultural Security Guidelines"
  },
  {
    "ofc_number": "OFC041",
    "option_text": "Implement comprehensive VIP transportation security protocols including vehicle screening, route security, and secure transportation procedures for high-profile guests.",
    "sheet": "VIP Security",
    "row": 41,
    "reference": "ASIS VIP Security Standards, Transportation Security Guidelines",
    "category": "VIP Security",
    "priority": "High",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V041",
    "benefit_explanation": "Ensures VIP transportation security, prevents vehicle-based attacks, and provides comprehensive route security",
    "advisory_impact": "Aligns with ASIS VIP Security Standards and Transportation Security Guidelines"
  },
  {
    "ofc_number": "OFC042",
    "option_text": "Enhance recreational area access control with key card systems, monitoring, and security protocols for pools, fitness centers, and recreational facilities.",
    "sheet": "Recreational Security",
    "row": 42,
    "reference": "ASIS Recreational Security Standards, Pool Safety Guidelines",
    "category": "Recreational Security",
    "priority": "Medium",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V015",
    "benefit_explanation": "Prevents unauthorized recreational access, ensures guest safety, and provides comprehensive recreational security",
    "advisory_impact": "Aligns with ASIS Recreational Security Standards and Pool Safety Guidelines"
  },
  {
    "ofc_number": "OFC043",
    "option_text": "Alternate mitigation for the same VIP staff / Security Force credential signals as V016: document roles, access tiers, and re-check cadence; integrate with HR and vendor management when contractor fields exist.",
    "sheet": "Vendor Security",
    "row": 43,
    "reference": "ASIS Vendor Security Standards, Contractor Screening Guidelines",
    "category": "Vendor Security",
    "priority": "High",
    "implementation_time": "2-6 months",
    "vulnerability_id": "V016",
    "benefit_explanation": "Prevents insider threats, ensures vendor security, and provides comprehensive contractor screening",
    "advisory_impact": "Aligns with ASIS Vendor Security Standards and Contractor Screening Guidelines"
  },
  {
    "ofc_number": "OFC044",
    "option_text": "Enhance vertical circulation security with elevator access control, stairwell monitoring, and comprehensive security measures for multi-story facilities.",
    "sheet": "Vertical Security",
    "row": 44,
    "reference": "ASIS Vertical Security Standards, Elevator Security Guidelines",
    "category": "Vertical Security",
    "priority": "Medium",
    "implementation_time": "3-5 months",
    "vulnerability_id": "V044",
    "benefit_explanation": "Prevents unauthorized vertical access, ensures multi-story security, and provides comprehensive vertical circulation security",
    "advisory_impact": "Aligns with ASIS Vertical Security Standards and Elevator Security Guidelines"
  },
  {
    "ofc_number": "OFC045",
    "option_text": "Implement comprehensive public area monitoring and control systems including surveillance, access control, and security protocols for lobbies, restaurants, and common spaces.",
    "sheet": "Public Area Security",
    "row": 45,
    "reference": "ASIS Public Area Security Standards, Lobby Security Guidelines",
    "category": "Public Area Security",
    "priority": "Medium",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V045",
    "benefit_explanation": "Ensures public area security, prevents high-traffic area incidents, and provides comprehensive public space security",
    "advisory_impact": "Aligns with ASIS Public Area Security Standards and Lobby Security Guidelines"
  },
  {
    "ofc_number": "OFC046",
    "option_text": "Develop comprehensive incident management and response protocols including crisis management procedures, emergency coordination, and incident escalation procedures.",
    "sheet": "Incident Management",
    "row": 46,
    "reference": "ASIS Incident Management Standards, Crisis Response Guidelines",
    "category": "Incident Management",
    "priority": "High",
    "implementation_time": "4-6 months",
    "vulnerability_id": "V019",
    "benefit_explanation": "Ensures effective incident response, prevents crisis management failures, and provides comprehensive emergency coordination",
    "advisory_impact": "Aligns with ASIS Incident Management Standards and Crisis Response Guidelines"
  },
  {
    "ofc_number": "OFC047",
    "option_text": "Implement comprehensive system redundancy and backup procedures including backup systems, redundancy protocols, and continuity of operations procedures.",
    "sheet": "System Redundancy",
    "row": 47,
    "reference": "ASIS System Redundancy Standards, Backup System Guidelines",
    "category": "System Redundancy",
    "priority": "High",
    "implementation_time": "4-8 months",
    "vulnerability_id": "V020",
    "benefit_explanation": "Ensures system reliability, prevents system failures, and provides comprehensive continuity of operations",
    "advisory_impact": "Aligns with ASIS System Redundancy Standards and Backup System Guidelines"
  },
  {
    "ofc_number": "OFC048",
    "option_text": "Implement comprehensive data protection and privacy measures including encryption, access controls, and compliance with privacy regulations (GDPR, CCPA).",
    "sheet": "Data Protection",
    "row": 48,
    "reference": "GDPR, CCPA, ASIS Data Protection Standards",
    "category": "Data Protection",
    "priority": "High",
    "implementation_time": "3-6 months",
    "vulnerability_id": "V021",
    "benefit_explanation": "Ensures data security, prevents data breaches, and provides comprehensive privacy protection",
    "advisory_impact": "Aligns with GDPR, CCPA, and ASIS Data Protection Standards"
  },
  {
    "ofc_number": "OFC049",
    "option_text": "Alternate mitigation for the same finding as OFC022: secure the delivery supply path (vendor lists, delivery schedules, sealed load verification at handoff, dispute resolution for suspicious deliveries). Remains physical security only—not food safety regulation.",
    "sheet": "Physical Security",
    "row": 49,
    "reference": "CISA physical security resources; DHS critical infrastructure partnership materials",
    "category": "Physical Security",
    "priority": "Medium",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V022",
    "benefit_explanation": "Adds layered controls on how deliveries enter the property and transfer to receiving staff",
    "advisory_impact": "Supports operational security; food safety compliance is outside HOST scope"
  },
  {
    "ofc_number": "OFC050",
    "option_text": "Implement comprehensive service area security measures including access control, monitoring, and security protocols for housekeeping, maintenance, and utility spaces.",
    "sheet": "Service Area Security",
    "row": 50,
    "reference": "ASIS Service Area Security Standards, Operational Security Guidelines",
    "category": "Service Area Security",
    "priority": "Medium",
    "implementation_time": "2-4 months",
    "vulnerability_id": "V050",
    "benefit_explanation": "Ensures operational security, prevents service area incidents, and provides comprehensive service area protection",
    "advisory_impact": "Aligns with ASIS Service Area Security Standards and Operational Security Guidelines"
  }
];

// Helper function to get option by ID
window.getOptionById = function(ofcNumber) {
  return window.VOFC_OPTIONS.find(o => o.ofc_number === ofcNumber);
};

// Helper function to get options by category
window.getOptionsByCategory = function(category) {
  return window.VOFC_OPTIONS.filter(o => o.category === category);
};

// Helper function to get options by priority
window.getOptionsByPriority = function(priority) {
  return window.VOFC_OPTIONS.filter(o => o.priority === priority);
};

// Helper function to get options for specific vulnerability
window.getOptionsForVulnerability = function(vulnerabilityId) {
  return window.VOFC_OPTIONS.filter(o => o.vulnerability_id === vulnerabilityId);
};

console.log('VOFC Options loaded:', window.VOFC_OPTIONS.length, 'options available');
