export {
  DependencyContractSchema,
  DependencyGateSchema,
  ImpactCurveInputsSchema,
  ContractAssetSchema,
  RedundancyAttributesSchema,
  BackupCapabilitySchema,
  RestorationCoordinationSchema,
  QuestionVulnerabilityTriggerSchema,
  REQUIRED_NARRATIVE_TOKENS,
  DependencyTypeSchema,
  AssetDesignationSchema,
  BackupScopeSchema,
  QuestionHelpSchema,
} from './dependency_contract';
export type {
  DependencyContract,
  DependencyGate,
  ImpactCurveInputs,
  ContractAsset,
  RedundancyAttributes,
  BackupCapability,
  RestorationCoordination,
  QuestionVulnerabilityTrigger,
  RequiredNarrativeToken,
  DependencyType,
  AssetDesignation,
  BackupScope,
  QuestionHelp,
} from './dependency_contract';

export {
  AssessmentSchema,
  AgreementsSchema,
  CategoryCodeSchema,
  CategoryInputSchema,
  CriticalProductRowSchema,
  PraCategorySchema,
  PriorityRestorationSchema,
  PriorityRestorationTopicSchema,
  CurveStorageSchema,
  InfrastructureNodeSchema,
  InfrastructureStateSchema,
  SlaFailureFlagValueSchema,
  SlaFailureFlagsSchema,
  SlaMttrSourceSchema,
  SupplySchema,
  SupplySourceSchema,
  SupplyIndependenceSchema,
  ItPhysicalPathDiversitySchema,
  ItTransportResilienceSchema,
  HostedContinuitySurvivabilitySchema,
  ItHostedResilienceEntrySchema,
  ItHostedResilienceSchema,
  ItCircuitCountSchema,
  ItCarrierDiversitySchema,
  ItBuildingEntryDiversitySchema,
  ItUpstreamPopDiversitySchema,
  ItFailoverSchema,
  EquipmentSupplierEntrySchema,
  AlternativeProvidersSchema,
  MaintenanceScheduleSchema,
  MonitoringCapabilitiesSchema,
  RedundancyInitiationModeSchema,
  RedundancyActivationSchema,
  CrossDependencySchema,
  CrossDependencyEdgeSchema,
  CrossDependencyCircularSchema,
  CrossDependencyCommonModeSchema,
  CrossDependenciesNodeSchema,
  CrossDependenciesDerivedSchema,
  CrossDependencyCategorySchema,
  CrossDependencyPurposeSchema,
  CrossDependencyCriticalitySchema,
  CrossDependencyTimeBucketSchema,
  CrossDependencySinglePathSchema,
  CrossDependencyConfidenceSchema,
  CrossDependencySourceSchema,
  type Assessment,
  type Agreements,
  type CategoryCode,
  type CategoryInput,
  type CriticalProductRow,
  type PraCategory,
  type PriorityRestoration,
  type PriorityRestorationTopic,
  type CurveStorage,
  type InfrastructureNode,
  type InfrastructureState,
  type SlaFailureFlagValue,
  type SlaFailureFlags,
  type SlaMttrSource,
  type Supply,
  type SupplySource,
  type SupplyIndependence,
  type ItPhysicalPathDiversity,
  type ItTransportResilience,
  type HostedContinuitySurvivability,
  type ItHostedResilienceEntry,
  type ItHostedResilience,
  type ItCircuitCount,
  type ItCarrierDiversity,
  type ItBuildingEntryDiversity,
  type ItUpstreamPopDiversity,
  type ItFailover,
  type EquipmentSupplierEntry,
  type AlternativeProviders,
  type MaintenanceSchedule,
  type MonitoringCapabilities,
  type RedundancyInitiationMode,
  type RedundancyActivation,
  type CrossDependency,
  type CrossDependencyEdge,
  type CrossDependencyCircular,
  type CrossDependencyCommonMode,
  type CrossDependenciesNode,
  type CrossDependenciesDerived,
  type CrossDependencyCategory,
  type CrossDependencyPurpose,
  type CrossDependencyCriticality,
  type CrossDependencyTimeBucket,
  type CrossDependencySinglePath,
  type CrossDependencyConfidence,
  type CrossDependencySource,
} from './assessment';

export type {
  UIFieldConfig,
  UICategoryConfig,
  UICategoryTableConfig,
  UICategoryTableColumn,
  UILabelSource,
  UIHelpSource,
} from './ui_config';
export { UI_CONFIG } from './ui_config.generated';
export {
  AGREEMENTS_FIELD_ORDER,
  AGREEMENTS_LABELS,
  PRA_CATEGORY_OPTIONS,
} from './agreements_ui_config';
export { getFieldHelp } from './ui_help';
export type { FieldHelpResult } from './ui_help';
export { storedToDisplayPercent, displayToStoredPercent } from './percent_display';
export { TOOL_VERSION, TEMPLATE_VERSION, BUILD_ID } from './build_info';
export {
  REQUIRED_TEMPLATE_ANCHORS,
  type TemplateAnchor,
} from './template_anchors';
export { TEMPLATE_ANCHOR_GUIDANCE } from './template_anchor_guidance';

export {
  VOFCSeveritySchema,
  VOFCApplicabilitySchema,
  VOFCOriginSchema,
  VOFCSchema,
  VOFCCollectionSchema,
  CALIBRATION_REASON_MAX_LENGTH,
  type VOFCSeverity,
  type VOFCApplicability,
  type VOFCOrigin,
  type VOFC,
  type VOFCCollection,
} from './vofc';

export {
  SECTOR_IDS,
  type VofcSectorId,
  type EvidenceItem,
  type VofcVulnerability,
  type VofcSectorReport,
  type VofcNarrative,
} from './vofc_narrative';

import { AssessmentSchema } from './assessment';
import type { Assessment } from './assessment';

export function parseAssessment(data: unknown): Assessment {
  return AssessmentSchema.parse(data);
}
