/**
 * Question-to-Condition Map
 * Single source of truth: every captured assessment key maps to a normalized condition.
 * Built from actual stored JSON keys (schema, coverage_manifest, dependency specs).
 */

export type SectorKey =
  | 'ELECTRIC_POWER'
  | 'COMMUNICATIONS'
  | 'INFORMATION_TECHNOLOGY'
  | 'WATER'
  | 'WASTEWATER';

export type ConditionKey =
  | 'requires_service'
  | 'provider_confirmed'
  | 'single_provider_or_path'
  | 'entry_diversity'
  | 'corridor_colocated'
  | 'alternate_present'
  | 'alternate_duration_hours'
  | 'alternate_materially_reduces_loss'
  | 'redundancy_initiation_mode'
  | 'restoration_priority_established'
  | 'recovery_hours'
  | 'time_to_impact_hours'
  | 'pace_depth'
  | 'pace_layers_present'
  | 'pace_layer_labels'
  /** Keys captured but not used in normalization (PRA/SLA, vehicle impact, repeatable tables, etc.). */
  | 'passthrough';

export type QuestionMapEntry = {
  sector: SectorKey;
  questionId: string;
  mapsTo: ConditionKey;
  transform?: 'bool' | 'enum' | 'number' | 'string' | 'paceDepth' | 'paceLayers';
  notes?: string;
};

export const QUESTION_CONDITION_MAP: QuestionMapEntry[] = [
  // ─── ELECTRIC_POWER ─────────────────────────────────────────────────────
  { sector: 'ELECTRIC_POWER', questionId: 'requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'ELECTRIC_POWER', questionId: 'curve_requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-2', mapsTo: 'provider_confirmed', transform: 'enum', notes: 'substations known' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-2_can_identify_substations', mapsTo: 'provider_confirmed', transform: 'enum' },
  { sector: 'ELECTRIC_POWER', questionId: 'curve_primary_provider', mapsTo: 'provider_confirmed', transform: 'string' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-3', mapsTo: 'single_provider_or_path', transform: 'number', notes: 'connection count' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-3_more_than_one_connection', mapsTo: 'single_provider_or_path', transform: 'enum' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-4', mapsTo: 'entry_diversity', transform: 'enum', notes: 'service connections array' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-4_physically_separated', mapsTo: 'entry_diversity', transform: 'enum' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-4', mapsTo: 'corridor_colocated', transform: 'enum', notes: 'shared_corridor in entries' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-4_physically_separated', mapsTo: 'corridor_colocated', transform: 'enum', notes: 'true=separated=NO colocated' },
  { sector: 'ELECTRIC_POWER', questionId: 'has_backup_any', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'ELECTRIC_POWER', questionId: 'has_backup', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'ELECTRIC_POWER', questionId: 'curve_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-8_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'ELECTRIC_POWER', questionId: 'has_backup_generator', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'ELECTRIC_POWER', questionId: 'backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'curve_backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'curve_loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'curve_loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-11', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-11_priority_restoration', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'ELECTRIC_POWER', questionId: 'recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'curve_recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'redundancy_activation', mapsTo: 'redundancy_initiation_mode', notes: 'mode, activation_delay_min; read via custom logic' },
  { sector: 'ELECTRIC_POWER', questionId: 'time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'curve_time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'ELECTRIC_POWER', questionId: 'agreements', mapsTo: 'passthrough', notes: 'PRA/SLA' },
  { sector: 'ELECTRIC_POWER', questionId: 'maintenance_schedule', mapsTo: 'passthrough', notes: 'backup maintenance and testing' },
  { sector: 'ELECTRIC_POWER', questionId: 'monitoring_capabilities', mapsTo: 'passthrough', notes: 'monitoring and alerting detail' },
  { sector: 'ELECTRIC_POWER', questionId: 'supply', mapsTo: 'passthrough', notes: 'supply sources' },
  { sector: 'ELECTRIC_POWER', questionId: 'vehicle_impact_exposure', mapsTo: 'passthrough', notes: 'E-7 derived' },
  { sector: 'ELECTRIC_POWER', questionId: 'vehicle_impact_protection', mapsTo: 'passthrough', notes: 'E-7a derived' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-2_substations', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-4_service_connections', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-5_single_supports_core_ops', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-5_core_ops_capable', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-6_exterior_protected', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-6_exterior_protections', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-7_vehicle_impact_exposure', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-7a_vehicle_impact_protection', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-9_refueling_plan', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-7_protected_vehicle_impact', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-3_service_connection_count', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-8_backup_power_available', mapsTo: 'passthrough', notes: 'E-8 yes/no; E-8_backup_assets is primary' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-8_backup_assets', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-9_refuel_sustainment_established', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-9_sustainment', mapsTo: 'passthrough', notes: 'fuel source/suppliers' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-10_tested_under_load', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-10_testing', mapsTo: 'passthrough', notes: 'test frequency/details' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-11_provider_restoration_coordination', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'backup_primary_method', mapsTo: 'passthrough', notes: 'deprecated legacy' },
  { sector: 'ELECTRIC_POWER', questionId: 'backup_capacity_pct', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'backup_type', mapsTo: 'passthrough' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-1_can_identify_providers', mapsTo: 'passthrough', notes: 'legacy/alternate provider question' },
  { sector: 'ELECTRIC_POWER', questionId: 'E-1_utility_providers', mapsTo: 'passthrough', notes: 'repeatable table' },

  // ─── COMMUNICATIONS ─────────────────────────────────────────────────────
  { sector: 'COMMUNICATIONS', questionId: 'requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'COMMUNICATIONS', questionId: 'curve_requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'COMMUNICATIONS', questionId: 'curve_primary_provider', mapsTo: 'provider_confirmed', transform: 'string' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_single_point_voice_failure', mapsTo: 'single_provider_or_path', transform: 'enum' },
  { sector: 'COMMUNICATIONS', questionId: 'comms_alternate_providers_or_paths', mapsTo: 'single_provider_or_path', transform: 'enum' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-1', mapsTo: 'provider_confirmed', transform: 'enum', notes: 'voice/data transport' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-2', mapsTo: 'passthrough', notes: 'comms transport' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-3', mapsTo: 'single_provider_or_path', transform: 'enum', notes: 'same carrier' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-4_same_geographic_location', mapsTo: 'entry_diversity', transform: 'enum', notes: 'path/termination diversity' },
  { sector: 'COMMUNICATIONS', questionId: 'has_backup', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'COMMUNICATIONS', questionId: 'has_backup_any', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'COMMUNICATIONS', questionId: 'curve_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'COMMUNICATIONS', questionId: 'backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'curve_backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'curve_loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'curve_loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_restoration_coordination', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'COMMUNICATIONS', questionId: 'recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'curve_recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'redundancy_activation', mapsTo: 'redundancy_initiation_mode', notes: 'mode, activation_delay_min; read via custom logic' },
  { sector: 'COMMUNICATIONS', questionId: 'time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'curve_time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_pace_P', mapsTo: 'pace_depth', transform: 'paceDepth' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_pace_A', mapsTo: 'pace_depth', transform: 'paceDepth' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_pace_C', mapsTo: 'pace_depth', transform: 'paceDepth' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_pace_E', mapsTo: 'pace_depth', transform: 'paceDepth' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_pace_P', mapsTo: 'pace_layers_present', transform: 'paceLayers' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_pace_A', mapsTo: 'pace_layers_present', transform: 'paceLayers' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_pace_C', mapsTo: 'pace_layers_present', transform: 'paceLayers' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_pace_E', mapsTo: 'pace_layers_present', transform: 'paceLayers' },
  { sector: 'COMMUNICATIONS', questionId: 'agreements', mapsTo: 'passthrough', notes: 'PRA/SLA' },
  { sector: 'COMMUNICATIONS', questionId: 'comms_single_provider_restoration', mapsTo: 'passthrough', notes: 'display-scoped restoration question' },
  { sector: 'COMMUNICATIONS', questionId: 'comms_restoration_constraints', mapsTo: 'passthrough', notes: 'restoration constraint detail' },
  { sector: 'COMMUNICATIONS', questionId: 'maintenance_schedule', mapsTo: 'passthrough', notes: 'backup maintenance and testing' },
  { sector: 'COMMUNICATIONS', questionId: 'monitoring_capabilities', mapsTo: 'passthrough', notes: 'monitoring and alerting detail' },
  { sector: 'COMMUNICATIONS', questionId: 'vehicle_impact_exposure', mapsTo: 'passthrough', notes: 'CO-7 derived' },
  { sector: 'COMMUNICATIONS', questionId: 'vehicle_impact_protection', mapsTo: 'passthrough', notes: 'CO-7a derived' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_voice_functions', mapsTo: 'passthrough' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_voice_functions_other_detail', mapsTo: 'passthrough' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-4_service_connections', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-4_physically_separated', mapsTo: 'passthrough' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-7', mapsTo: 'passthrough', notes: 'vehicle impact' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-7a', mapsTo: 'passthrough', notes: 'vehicle impact protection' },
  { sector: 'COMMUNICATIONS', questionId: 'CO-7_protected_vehicle_impact', mapsTo: 'passthrough' },
  { sector: 'COMMUNICATIONS', questionId: 'backup_capacity_pct', mapsTo: 'passthrough' },
  { sector: 'COMMUNICATIONS', questionId: 'backup_type', mapsTo: 'passthrough' },
  { sector: 'COMMUNICATIONS', questionId: 'supply', mapsTo: 'passthrough', notes: 'supply sources' },
  { sector: 'COMMUNICATIONS', questionId: 'comm_interoperability', mapsTo: 'passthrough', notes: 'interop/coordination' },

  // ─── INFORMATION_TECHNOLOGY ─────────────────────────────────────────────
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-1', mapsTo: 'provider_confirmed', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-1_can_identify_providers', mapsTo: 'provider_confirmed', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_primary_provider', mapsTo: 'provider_confirmed', transform: 'string' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_secondary_provider', mapsTo: 'passthrough', notes: 'secondary ISP; authoritative store is supply.sources' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-3', mapsTo: 'single_provider_or_path', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-3_redundancy_present', mapsTo: 'single_provider_or_path', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-3_multiple_connections', mapsTo: 'single_provider_or_path', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-4_physically_separated', mapsTo: 'entry_diversity', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-4_geographically_separated', mapsTo: 'corridor_colocated', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'has_backup', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'has_backup_any', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-8_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-11', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-11_restoration_coordination', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'redundancy_activation', mapsTo: 'redundancy_initiation_mode', notes: 'mode, activation_delay_min; read via custom logic' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'curve_time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'agreements', mapsTo: 'passthrough', notes: 'PRA/SLA' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'vehicle_impact_exposure', mapsTo: 'passthrough', notes: 'IT-7 derived' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'vehicle_impact_protection', mapsTo: 'passthrough', notes: 'IT-7a derived' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-4_service_connections', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-7_vehicle_impact_exposure', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-7a_vehicle_impact_protection', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-7_protected_vehicle_impact', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-1_service_providers', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-2_can_identify_assets', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-2_upstream_assets', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-3_connection_count', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-5_survivability', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-6_components_protected', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-6_protections', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-7_installation_location', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-8_backup_capabilities', mapsTo: 'passthrough', notes: 'repeatable table' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-9_sustainment_plan', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-9_plan_details', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-10_reliability_known', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'IT-11_restoration_coordination', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'it_continuity_plan_exists', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'it_plan_exercised', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'it_exercise_scope', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'backup_capacity_pct', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'backup_type', mapsTo: 'passthrough' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'it_installation_location', mapsTo: 'passthrough', notes: 'derived from IT-7_installation_location' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'equipment_suppliers', mapsTo: 'passthrough', notes: 'supply-chain supplier table' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'alternative_providers', mapsTo: 'passthrough', notes: 'supply-chain alternate providers' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'maintenance_schedule', mapsTo: 'passthrough', notes: 'backup maintenance and testing' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'monitoring_capabilities', mapsTo: 'passthrough', notes: 'monitoring and alerting detail' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'supply', mapsTo: 'passthrough', notes: 'supply sources' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'it_transport_resilience', mapsTo: 'passthrough', notes: 'circuit_count, carrier_diversity, building_entry_diversity' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'it_hosted_resilience', mapsTo: 'passthrough', notes: '3-state survivability per hosted dependency' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'network_segmentation', mapsTo: 'passthrough', notes: 'IT-SEGMENT-01 trigger' },
  { sector: 'INFORMATION_TECHNOLOGY', questionId: 'it_incident_response_owner', mapsTo: 'passthrough', notes: 'IT-IR-01 trigger' },

  // ─── WATER ──────────────────────────────────────────────────────────────
  { sector: 'WATER', questionId: 'requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'WATER', questionId: 'curve_requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'WATER', questionId: 'W_Q2', mapsTo: 'provider_confirmed', transform: 'enum' },
  { sector: 'WATER', questionId: 'curve_primary_provider', mapsTo: 'provider_confirmed', transform: 'string', notes: 'provider string present = CONFIRMED' },
  { sector: 'WATER', questionId: 'W_Q2_connection_count', mapsTo: 'single_provider_or_path', transform: 'number' },
  { sector: 'WATER', questionId: 'W_Q3', mapsTo: 'entry_diversity', transform: 'enum' },
  { sector: 'WATER', questionId: 'W_Q3_same_geographic_location', mapsTo: 'entry_diversity', transform: 'enum' },
  { sector: 'WATER', questionId: 'W_Q4', mapsTo: 'corridor_colocated', transform: 'enum' },
  { sector: 'WATER', questionId: 'W_Q4_collocated_corridor', mapsTo: 'corridor_colocated', transform: 'enum' },
  { sector: 'WATER', questionId: 'has_backup', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'WATER', questionId: 'has_backup_any', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'WATER', questionId: 'curve_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'WATER', questionId: 'W_Q8_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'WATER', questionId: 'W_Q8_alternate_source', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'WATER', questionId: 'backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'WATER', questionId: 'curve_backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'WATER', questionId: 'loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'WATER', questionId: 'curve_loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'WATER', questionId: 'loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'WATER', questionId: 'curve_loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'WATER', questionId: 'W_Q6', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'WATER', questionId: 'W_Q6_priority_restoration', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'WATER', questionId: 'recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'WATER', questionId: 'curve_recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'WATER', questionId: 'redundancy_activation', mapsTo: 'redundancy_initiation_mode', notes: 'mode, activation_delay_min; read via custom logic' },
  { sector: 'WATER', questionId: 'time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'WATER', questionId: 'curve_time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'WATER', questionId: 'agreements', mapsTo: 'passthrough', notes: 'PRA/SLA' },
  { sector: 'WATER', questionId: 'W_Q4', mapsTo: 'passthrough', notes: 'yes/no; W_Q4_collocated_corridor is primary' },
  { sector: 'WATER', questionId: 'W_Q8_alternate_source', mapsTo: 'passthrough', notes: 'alternate source detail' },
  { sector: 'WATER', questionId: 'backup_capacity_pct', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'backup_type', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'maintenance_schedule', mapsTo: 'passthrough', notes: 'backup maintenance and testing' },
  { sector: 'WATER', questionId: 'monitoring_capabilities', mapsTo: 'passthrough', notes: 'monitoring and alerting detail' },
  { sector: 'WATER', questionId: 'W_Q2', mapsTo: 'passthrough', notes: 'yes/no; W_Q2_connection_count is primary' },
  { sector: 'WATER', questionId: 'W_Q3', mapsTo: 'passthrough', notes: 'yes/no; W_Q3_same_geographic_location is primary' },
  { sector: 'WATER', questionId: 'W_Q6', mapsTo: 'passthrough', notes: 'yes/no; W_Q6_priority_restoration is primary' },
  { sector: 'WATER', questionId: 'W_Q8', mapsTo: 'passthrough', notes: 'yes/no; W_Q8_backup_available is primary' },
  { sector: 'WATER', questionId: 'supply', mapsTo: 'passthrough', notes: 'supply sources' },
  { sector: 'WATER', questionId: 'W_Q1_municipal_supply', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q7_contingency_plan', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q9_alternate_supports_core', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q10_alternate_depends_on_power', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q11_water_based_suppression', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q12_fire_secondary_supply', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q13_fire_impact_evaluated', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q14_onsite_pumping', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q15_backup_power_pumps', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q16_manual_override', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q17_pump_alarming', mapsTo: 'passthrough' },
  { sector: 'WATER', questionId: 'W_Q18_dual_source_parts', mapsTo: 'passthrough' },

  // ─── WASTEWATER ─────────────────────────────────────────────────────────
  { sector: 'WASTEWATER', questionId: 'requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'WASTEWATER', questionId: 'curve_requires_service', mapsTo: 'requires_service', transform: 'bool' },
  { sector: 'WASTEWATER', questionId: 'WW_Q2', mapsTo: 'provider_confirmed', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'curve_primary_provider', mapsTo: 'provider_confirmed', transform: 'string', notes: 'provider string present = CONFIRMED' },
  { sector: 'WASTEWATER', questionId: 'WW_Q2_connection_count', mapsTo: 'single_provider_or_path', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'WW_Q3', mapsTo: 'entry_diversity', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'WW_Q3_same_geographic_location', mapsTo: 'entry_diversity', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'WW_Q4', mapsTo: 'corridor_colocated', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'WW_Q4_collocated_corridor', mapsTo: 'corridor_colocated', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'has_backup', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'WASTEWATER', questionId: 'has_backup_any', mapsTo: 'alternate_present', transform: 'bool' },
  { sector: 'WASTEWATER', questionId: 'curve_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'WW_Q7_backup_available', mapsTo: 'alternate_present', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'curve_backup_duration_hours', mapsTo: 'alternate_duration_hours', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'curve_loss_fraction_no_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'curve_loss_fraction_with_backup', mapsTo: 'alternate_materially_reduces_loss', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'WW_Q6', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'WW_Q6_priority_restoration', mapsTo: 'restoration_priority_established', transform: 'enum' },
  { sector: 'WASTEWATER', questionId: 'recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'curve_recovery_time_hours', mapsTo: 'recovery_hours', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'redundancy_activation', mapsTo: 'redundancy_initiation_mode', notes: 'mode, activation_delay_min; read via custom logic' },
  { sector: 'WASTEWATER', questionId: 'time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'curve_time_to_impact_hours', mapsTo: 'time_to_impact_hours', transform: 'number' },
  { sector: 'WASTEWATER', questionId: 'agreements', mapsTo: 'passthrough', notes: 'PRA/SLA' },
  { sector: 'WASTEWATER', questionId: 'WW_Q4', mapsTo: 'passthrough', notes: 'yes/no; WW_Q4_collocated_corridor is primary' },
  { sector: 'WASTEWATER', questionId: 'backup_capacity_pct', mapsTo: 'passthrough' },
  { sector: 'WASTEWATER', questionId: 'backup_type', mapsTo: 'passthrough' },
  { sector: 'WASTEWATER', questionId: 'maintenance_schedule', mapsTo: 'passthrough', notes: 'backup maintenance and testing' },
  { sector: 'WASTEWATER', questionId: 'monitoring_capabilities', mapsTo: 'passthrough', notes: 'monitoring and alerting detail' },
  { sector: 'WASTEWATER', questionId: 'WW_Q2', mapsTo: 'passthrough', notes: 'yes/no; WW_Q2_connection_count is primary' },
  { sector: 'WASTEWATER', questionId: 'WW_Q3', mapsTo: 'passthrough', notes: 'yes/no; WW_Q3_same_geographic_location is primary' },
  { sector: 'WASTEWATER', questionId: 'WW_Q6', mapsTo: 'passthrough', notes: 'yes/no; WW_Q6_priority_restoration is primary' },
  { sector: 'WASTEWATER', questionId: 'WW_Q7', mapsTo: 'passthrough', notes: 'yes/no; WW_Q7_backup_available is primary' },
  { sector: 'WASTEWATER', questionId: 'supply', mapsTo: 'passthrough', notes: 'supply sources' },
  { sector: 'WASTEWATER', questionId: 'WW_Q1_discharge_to_sewer', mapsTo: 'passthrough', notes: 'doctrine-aligned WW_Q1–WW_Q14 schema' },
  { sector: 'WASTEWATER', questionId: 'WW_Q7_contingency_plan', mapsTo: 'passthrough', notes: 'contingency plan with utility' },
  { sector: 'WASTEWATER', questionId: 'WW_Q8_onsite_pumping', mapsTo: 'passthrough' },
  { sector: 'WASTEWATER', questionId: 'WW_Q9_backup_power_pumps', mapsTo: 'passthrough' },
  { sector: 'WASTEWATER', questionId: 'WW_Q10_manual_override', mapsTo: 'passthrough' },
  { sector: 'WASTEWATER', questionId: 'WW_Q11_pump_alarming', mapsTo: 'passthrough' },
  { sector: 'WASTEWATER', questionId: 'WW_Q12_dual_source_parts', mapsTo: 'passthrough' },
  { sector: 'WASTEWATER', questionId: 'WW_Q13_holding_capacity', mapsTo: 'passthrough' },
  { sector: 'WASTEWATER', questionId: 'WW_Q14_constraints_evaluated', mapsTo: 'passthrough' },
];

/** All question IDs that map to conditions (for accounting). */
export const MAPPED_QUESTION_IDS = new Set(QUESTION_CONDITION_MAP.map((e) => e.questionId));

/** Map entries by sector. */
export const MAP_BY_SECTOR: Record<SectorKey, QuestionMapEntry[]> = {
  ELECTRIC_POWER: QUESTION_CONDITION_MAP.filter((e) => e.sector === 'ELECTRIC_POWER'),
  COMMUNICATIONS: QUESTION_CONDITION_MAP.filter((e) => e.sector === 'COMMUNICATIONS'),
  INFORMATION_TECHNOLOGY: QUESTION_CONDITION_MAP.filter((e) => e.sector === 'INFORMATION_TECHNOLOGY'),
  WATER: QUESTION_CONDITION_MAP.filter((e) => e.sector === 'WATER'),
  WASTEWATER: QUESTION_CONDITION_MAP.filter((e) => e.sector === 'WASTEWATER'),
};
